[project]
name = "alterego"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=5.46.0",
    "openai>=1.108.0",
    "pypdf>=6.0.0",
]
